# Generated by Django 2.1a1 on 2018-11-05 13:04

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=250)),
                ('contenu', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdDossier', models.CharField(default='null', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(default='null', max_length=250)),
                ('valeur', models.CharField(max_length=25)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterielAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeIdentification', models.CharField(default='null', max_length=60)),
                ('etat', models.CharField(choices=[('A', 'Activer'), ('D', 'Desactiver')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MaterielMesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdMaterielMesure', models.CharField(default='null', max_length=250)),
                ('etat', models.CharField(choices=[('A', 'Activer'), ('D', 'Desactiver')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Specialization', models.CharField(default='Generaliste', max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MedecinAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateBegin', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('DateEnd', models.DateField(blank=True, null=True)),
                ('CodeIdentification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.MaterielAuth')),
                ('IdMedecin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.Medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPatient', models.CharField(max_length=250)),
                ('PrenomPatient', models.CharField(max_length=250)),
                ('DateNaissPatient', models.DateField()),
                ('Address', models.CharField(max_length=250)),
                ('Sexe', models.CharField(choices=[('F', 'Femme'), ('M', 'Homme')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdAttach', models.CharField(default='null', max_length=255)),
                ('IdChannel', models.CharField(default='null', max_length=30)),
                ('PublicKey', models.CharField(default='null', max_length=30)),
                ('DateBegin', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('DateEnd', models.DateField(blank=True, null=True)),
                ('IdMaterielMesure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.MaterielMesure')),
                ('IdPatient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='enregistrement',
            name='IdPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.Patient'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='IdMedecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.Medecin'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='IdPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.Patient'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='IdDossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='malchance.Dossier'),
        ),
    ]
